
trigger:
- master

variables:
  - template: .build/variables.yaml

stages:
  - stage: Build
    jobs:
      - job: build
        strategy:
          matrix:
            amd64:
              architecture: amd64
            i386:
              architecture: i386
            aarch64:
              architecture: aarch64
            armv7:
              architecture: armv7
            armhf:
              architecture: armhf
        steps:
          - template: .build/build-container.yaml

  - stage: Push
    jobs:
      - job: update_repository
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'filePath'
            filePath: '.build/push-to-repository.ps1'
          displayName: 'Push to repository'
